version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ao-platform-db
    environment:
      POSTGRES_DB: ao_platform
      POSTGRES_USER: ao_user
      POSTGRES_PASSWORD: SuperStrongPassword159
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ao-network

  redis:
    image: redis:7-alpine
    container_name: ao-platform-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - ao-network

  app:
    build: .
    container_name: ao-platform-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://ao_user:SuperStrongPassword159@postgres:5432/ao_platform
      JWT_SECRET: 654de28a7a72a9ee13413bb248af5df2c0c428ba2e92809a0766037d34c8578928f27191f707789d5cdec0de22b400d46a1dcf2ef8fa55bb0f89d8c7deb48c18
      JWT_REFRESH_SECRET: 5ebf83866a6ff6db5e0baa104f54a0c595a4e75246a187a06c169c8861ed0f8d77243a93406fb5a9ae8206022104fa2e1d2b62ab92259b8090fb8350803ca84b
      JWT_EXPIRE: 15m
      JWT_REFRESH_EXPIRE: 7d
      ADMIN_EMAIL: omran.a.jr@gmail.com
      ADMIN_PASSWORD: ao.totti.jr.10
      CLOUDINARY_CLOUD_NAME: dpd3kjym1
      CLOUDINARY_API_KEY: 625224553868647
      CLOUDINARY_API_SECRET: 01MKowxDvVI4kDSE-sSY1qoMuQM
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
      FRONTEND_URL: http://localhost:3000
      ADMIN_URL: http://localhost:3001
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ao-network
    volumes:
      - uploads:/app/uploads

volumes:
  postgres_data:
  uploads:

networks:
  ao-network:
    driver: bridge
